#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Error: Please provide a package version argument" 1>&2
  exit 1
fi

pkg_name="@poap-xyz/poap-sdk"
pkg_version="$1"

if [[ ! $pkg_version =~ ^v[0-9]+\.[0-9]+\.[0-9]+-beta-[0-9]+$ ]]; then
  echo "Error: Please provide a package BETA version ($pkg_version given)" 1>&2
  exit 1
fi

echo "New BETA package $pkg_name@$pkg_version.."

echo
echo "Setting version $pkg_version for $pkg_name.."
if ! pnpm pkg set version="$pkg_version"; then
  echo "Error: Failed to set version $pkg_version for $pkg_name" 1
  exit 1
fi

echo
echo "Building package $pkg_name@$pkg_version.."
if ! pnpm build; then
  echo "Error: Failed to build $pkg_name@$pkg_version" 1>&2
  exit 1
fi

echo
echo "Publishing package $pkg_name@$pkg_version.."
if ! pnpm publish --no-git-checks --tag beta --access public; then
  echo "Error: Failed to publish $pkg_name@$pkg_version" 1>&2
  exit 1
fi

echo "$pkg_name@$pkg_version published"
