#!/usr/bin/env bash
set -euo pipefail

pkg_name="@poap-xyz/poap-sdk"

echo "Package $pkg_name.."

local_version=$(jq -r '.version' package.json)
remote_version=$(pnpm info "$pkg_name" version --json 2>/dev/null | jq -r '.[0] // .')

echo
echo "Building package $pkg_name@$local_version.."
if ! pnpm build; then
  echo "Error: Failed to build $pkg_name@$local_version" 1>&2
  exit 1
fi

# Check if the package exists remotely or if the version has changed
if [ -z "$remote_version" ] || [ "$local_version" != "$remote_version" ]; then
  if [ -z "$remote_version" ]; then
    echo "Package $pkg_name not found in registry. Deploying for the first time."
  else
    echo "Detected version change in $pkg_name: $remote_version -> $local_version"
  fi

  if ! pnpm publish --access public; then
    echo "Error: Failed publish $pkg_name"
    exit 1
  fi
else
  echo "No version change detected for $pkg_name"
fi
